# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:20:13+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field


class Sort(Enum):
    created_at = 'created_at'
    field_created_at = '-created_at'
    original_created_at = 'original_created_at'
    field_original_created_at = '-original_created_at'
    name = 'name'
    field_name = '-name'


class Filter(BaseModel):
    pass


class Page(BaseModel):
    pass


class Attributes(BaseModel):
    end_time: float = Field(..., examples=[12.3])
    media_id: str = Field(..., examples=['9b9a2e82-5b47-4f59-831d-4c239824b983'])
    name: str = Field(..., examples=['Example New Clip'])
    start_time: float = Field(..., examples=[10.1])


class Data(BaseModel):
    attributes: Attributes


class ApiV1ClipsPostRequest(BaseModel):
    data: Data


class Attributes1(BaseModel):
    end_time: Optional[float] = Field(None, examples=[12.3])
    name: Optional[str] = Field(None, examples=['Example Clip'])
    start_time: Optional[float] = Field(None, examples=[10.1])


class Data1(BaseModel):
    attributes: Attributes1


class ApiV1ClipsIdPutRequest(BaseModel):
    data: Data1


class Attributes2(BaseModel):
    description: Optional[str] = Field(None, examples=['Video description'])
    name: Optional[str] = Field(None, examples=['Video name'])
    source_url: Optional[str] = Field(
        None,
        examples=[
            '(required if importing a video from a source url) https://archive.org/download/SF143/SF143_512kb.mp4'
        ],
    )
    upload_id: Optional[str] = Field(
        None,
        examples=[
            '(required if uploading a local file) ey399vjdkdjf0jslcjd0wjc0ujffj3432lo23kk2o22'
        ],
    )


class Data2(BaseModel):
    attributes: Attributes2


class ApiV1MediasPostRequest(BaseModel):
    data: Data2


class Attributes3(BaseModel):
    created_at: Optional[str] = Field(None, examples=['2022-10-14T21:23:42.659Z'])
    description: Optional[str] = Field(
        None,
        examples=[
            "Enos was the second chimpanzee launched into space by NASA. He was the first and only chimpanzee, and third hominid after cosmonauts Yuri Gagarin and Gherman Titov, to achieve Earth orbit. Enos's flight occurred on November 29, 1961. More details: https://en.wikipedia.org/wiki/Enos_(chimpanzee)"
        ],
    )
    external_id: Optional[str] = Field(None, examples=['1'])
    has_fetch_error: Optional[bool] = Field(None, examples=[False])
    is_processing: Optional[bool] = Field(None, examples=[False])
    name: Optional[str] = Field(None, examples=['Chimp Into Space'])
    original_created_at: Optional[str] = Field(
        None, examples=['2022-10-14T21:23:42.659Z']
    )
    processing_started_at: Optional[str] = Field(
        None, examples=['2022-10-14T21:23:42.628Z']
    )
    source_created_at: Optional[str] = Field(
        None, examples=['2022-10-14T21:23:42.659Z']
    )
    source_file_content_type: Optional[str] = Field(None, examples=['video/mp4'])
    source_file_duration: Optional[float] = Field(None, examples=['98.865532'])
    source_file_height: Optional[float] = Field(None, examples=[280])
    source_file_preview_image_url: Optional[str] = Field(
        None, examples=['https://www.example.com/path-to-image']
    )
    source_file_width: Optional[float] = Field(None, examples=[320])
    source_url: Optional[str] = Field(
        None, examples=['https://archive.org/download/SF143/SF143_512kb.mp4']
    )


class Datum(BaseModel):
    id: Optional[str] = Field(None, examples=['9b9a2e82-5b47-4f59-831d-4c239824b983'])
    type: Optional[str] = Field(None, examples=['clips'])


class Clips(BaseModel):
    data: Optional[List[Datum]] = None


class Relationships(BaseModel):
    clips: Optional[Clips] = None


class Data4(BaseModel):
    id: Optional[str] = Field(None, examples=['9b9a2e82-5b47-4f59-831d-4c239824b983'])
    type: Optional[str] = Field(None, examples=['transcriptions'])


class Transcription(BaseModel):
    data: Optional[Data4] = None


class Data3(BaseModel):
    attributes: Optional[Attributes3] = None
    id: Optional[str] = Field(None, examples=['9b9a2e82-5b47-4f59-831d-4c239824b983'])
    relationships: Optional[Relationships] = None
    transcription: Optional[Transcription] = None
    type: Optional[str] = Field(None, examples=['medias'])


class Attributes4(BaseModel):
    created_at: Optional[str] = Field(None, examples=['2022-10-14T21:23:42.628Z'])
    end_char: Optional[str] = Field(None, examples=[1303])
    end_time: Optional[float] = Field(None, examples=['96.63'])
    external_id: Optional[str] = Field(None, examples=['1'])
    media_file_content_type: Optional[str] = Field(None, examples=['video/mp4'])
    media_file_duration: Optional[float] = Field(None, examples=[38.938939])
    media_file_height: Optional[float] = Field(None, examples=[240])
    media_file_preview_image_url: Optional[str] = Field(
        None, examples=['https://www.example.com/path-to-image']
    )
    media_file_url: Optional[str] = Field(
        None, examples=['https://www.example.com/path-to-video']
    )
    media_file_width: Optional[float] = Field(None, examples=[320])
    name: Optional[str] = Field(
        None, examples=['john h. glenn, kindly air force base hospital']
    )
    rank: Optional[int] = Field(None, examples=[0])
    start_char: Optional[int] = Field(None, examples=[737])
    start_time: Optional[float] = Field(None, examples=['57.71'])
    text: Optional[str] = Field(
        None,
        examples=[
            'He landed in the sea south of Bermuda and has brought to the islands for quick medical checks before he is taken back to Cape Canaveral for a thorough examination. Scientists are related at the condition of both chimp and capsule. They came through the test in a manner that brings a man flight closer to reality for the U. S. Space team at Kindly Air Force Base Hospital, Enos appears sound, if not happy to examining doctors. He performed his task well, not missing a trick in the complex series of work assignments next in orbit, Lieutenant Colonel John H. Glenn.'
        ],
    )


class Data5(BaseModel):
    id: Optional[str] = Field(None, examples=['9b9a2e82-5b47-4f59-831d-4c239824b983'])
    type: Optional[str] = Field(None, examples=['medias'])


class Media(BaseModel):
    data: Optional[Data5] = None


class Relationships1(BaseModel):
    media: Optional[Media] = None


class Included(BaseModel):
    attributes: Optional[Attributes4] = None
    id: Optional[str] = Field(None, examples=['9b9a2e82-5b47-4f59-831d-4c239824b983'])
    relationships: Optional[Relationships1] = None
    type: Optional[str] = Field(None, examples=['clips'])


class Attributes5(BaseModel):
    text: Optional[str] = Field(
        None,
        examples=[
            'He landed in the sea south of Bermuda and has brought to the islands for quick medical checks before he is taken back to Cape Canaveral for a thorough examination. Scientists are related at the condition of both chimp and capsule. They came through the test in a manner that brings a man flight closer to reality for the U. S. Space team at Kindly Air Force Base Hospital, Enos appears sound, if not happy to examining doctors. He performed his task well, not missing a trick in the complex series of work assignments next in orbit, Lieutenant Colonel John H. Glenn.'
        ],
    )


class Included1(BaseModel):
    attributes: Optional[Attributes5] = None
    id: Optional[str] = Field(None, examples=['9b9a2e82-5b47-4f59-831d-4c239824b983'])
    relationships: Optional[Dict[str, Any]] = None
    type: Optional[str] = Field(None, examples=['transcriptions'])


class Payload(BaseModel):
    data: Optional[Data3] = None
    included: Optional[List[Union[Included, Included1]]] = None


class ProvidedURLInWebhookSubscriptionsPostRequest(BaseModel):
    event: Optional[str] = Field(None, examples=['media.processing_finished'])
    payload: Optional[Payload] = None


class Attributes6(BaseModel):
    description: Optional[str] = Field(
        None, examples=['Writing by Sam Denby; Research by Sam Denby and Tristan Purdy']
    )
    name: Optional[str] = Field(
        None, examples=['Why Electric Planes are Inevitably Coming']
    )


class Data6(BaseModel):
    attributes: Attributes6


class ApiV1MediasIdPutRequest(BaseModel):
    data: Data6


class Attributes7(BaseModel):
    subscribed_events: Optional[List] = Field(
        None, examples=[['media.processing_finished']]
    )
    url: str = Field(..., examples=['https://example.com/contentgroove_webhooks/12345'])


class Data7(BaseModel):
    attributes: Attributes7


class ApiV1WebhookSubscriptionsPostRequest(BaseModel):
    data: Data7
